# TwitCurl configuration file

loglevel: 0
hashtags: newgirl, foo, wtf, goldstar
tag_search: 0
# public search curls through all tweets, private curls your timeline 
# or add a username (without the @)
search_type: comic_fanboy
